list(REMOVE_ITEM ${PROJECT_NAME}_HEADER_FILES CMakeLists.txt)
#install(FILES ${${PROJECT_NAME}_HEADER_FILES}
#	DESTINATION include/${PROJECT_NAME})
if (BUILD_SHARED_LIBS)
	if (EXISTS ${CMAKE_SYSROOT}/usr/lib/${ARCH}-linux-gnu)
		set(_LIB lib/${ARCH}-linux-gnu)
	elseif (EXISTS /lib64)
		set(_LIB lib64)
	else ()
		set(_LIB lib)
	endif ()
	install(TARGETS ${PROJECT_NAME} DESTINATION ${_LIB})
endif ()
