list(REMOVE_ITEM ${PROJECT_NAME}_HEADER_FILES CMakeLists.txt)
#install(FILES ${${PROJECT_NAME}_HEADER_FILES}
#	DESTINATION include/${PROJECT_NAME})
if (BUILD_SHARED_LIBS)
	install(TARGETS ${PROJECT_NAME} DESTINATION lib)
endif ()
